#!/bin/bash
set -e
bin/rails code:syntax
# nvm use 22
# bin/rails test

source .env.production
# SECRET_KEY_BASE=fdfasdfdasfdsa RAILS_ENV=production bundle exec rails assets:precompile
# git add .
# git commit -m "asset compiles"
# git push origin main
bundle exec kamal deploy
unset DATABASE_URL