default: &default
  #adapter: postgresql
  adapter: postgis 
  encoding: unicode
  pool: 5
  timeout: 5000
  port: 5432
  # username: pcdbu
  # password: 17Xp860gpSpu8Of0N2WkeHpJ/Kg=

development:
  primary:
    <<: *default
    database: pollitify_hub_development
    host: localhost

  reporting:
    <<: *default
    database: pollitify_hub_reporting_development
    host: localhost

test:
  <<: *default
  database: pollitify_hub_test
  host: localhost
  
# queue:
#   <<: *default
#   database: polly_development_queue
#   migrations_paths: db/queue_migrate

    
#
# NOTE: REQUIRED FOR DOCKERIZED ASSET COMPILATION
# HERE THERE BE DRAGONS
#
production:
  adapter: postgresql

# production:
#   primary:
#     url: <%= ENV["DATBASE_URL"] %>
#   cable:
#     adapter: solid_cable
#     #adapter: postgresql
#     username: polly
#     password: <%= ENV["APP_DATABASE_PASSWORD"] %>
#     database: polly_production_cable
#     migrations_paths: db/cable_migrate
